	worker_processes  1;
	pid /mnt/c/Users/User/Documents/github/codam/websev_liath/NGINX_practice/nginx_lab_run/prefix/nginx.pid;
	error_log /mnt/c/Users/User/Documents/github/codam/websev_liath/NGINX_practice/nginx_lab_run/logs/bootstrap_error.log info;

	events {
		worker_connections  128;
	}

	http {
		default_type  text/plain;
		access_log  /mnt/c/Users/User/Documents/github/codam/websev_liath/NGINX_practice/nginx_lab_run/logs/access.log;
		error_log   /mnt/c/Users/User/Documents/github/codam/websev_liath/NGINX_practice/nginx_lab_run/logs/error.log info;

		server {
			listen 8080;
			server_name localhost;

			root /mnt/c/Users/User/Documents/github/codam/websev_liath/NGINX_practice/nginx_lab_run/playground/www;
			autoindex on;

			location / {
				try_files $uri $uri/ =404;
			}

			location /uploads/ {
				alias /mnt/c/Users/User/Documents/github/codam/websev_liath/NGINX_practice/nginx_lab_run/playground/uploads/;
				autoindex on;
			}
		}
	}
