#!/usr/bin/env bash

# Exit on first error (-e), fail on undefined vars (-u),
# and propagate pipeline failures (-o pipefail).
set -euo pipefail

# Base folder where this script lives.
BASE_DIR="$(cd "$(dirname "$0")" && pwd)"

# One isolated run folder. Everything generated by the script goes here.
RUN_DIR="$BASE_DIR/nginx_lab_run"

# NGINX runtime prefix directory (pid and relative runtime paths).
PREFIX_DIR="$RUN_DIR/prefix"

# Generated NGINX config directory.
CONF_DIR="$RUN_DIR/conf"

# NGINX log output directory.
LOG_DIR="$RUN_DIR/logs"

# Playground root that imitates a mini website filesystem.
PLAYGROUND_DIR="$RUN_DIR/playground"

# Website root served by NGINX.
WWW_DIR="$PLAYGROUND_DIR/www"

# Directory used for upload-related route experiments.
UPLOAD_DIR="$PLAYGROUND_DIR/uploads"

# Raw HTTP request files saved here.
REQ_DIR="$RUN_DIR/requests"

# Raw HTTP response files saved here.
RESP_DIR="$RUN_DIR/responses"

# Filesystem snapshots (before/after tests).
SNAP_DIR="$RUN_DIR/snapshots"

# Human-readable run summary report.
REPORT_FILE="$RUN_DIR/report.txt"

# Default listen port (can be overridden: PORT=8090 ./nginx_lab.sh)
PORT="${PORT:-8080}"

# NGINX binary path (can be overridden: NGINX_BIN=/usr/sbin/nginx ...)
NGINX_BIN="${NGINX_BIN:-nginx}"

# Bootstrap-level stderr/stdout from nginx commands gets collected here.
NGINX_BOOTSTRAP_ERR="$LOG_DIR/bootstrap_error.log"

# Called automatically on script exit (success or failure).
# It tries to gracefully stop the isolated nginx instance.
cleanup() 
{
    # Use the same prefix+config so we target the nginx started by this script only.
    # Redirect output to bootstrap log so terminal output stays clean.
    if "$NGINX_BIN" -g "error_log $NGINX_BOOTSTRAP_ERR info;" -p "$PREFIX_DIR/" -c "$CONF_DIR/nginx.conf" -s quit >>"$NGINX_BOOTSTRAP_ERR" 2>&1; then
        # no-op: command succeeded.
        :
    fi
}

# Check that required external tools exist before doing any work.
require_tools() 
{
    command -v "$NGINX_BIN" >/dev/null 2>&1 || { echo "[ERR] nginx not found. Install nginx or set NGINX_BIN=/path/to/nginx"; exit 1; }
    command -v nc >/dev/null 2>&1 || { echo "[ERR] nc (netcat) not found"; exit 1; }
    command -v timeout >/dev/null 2>&1 || { echo "[ERR] timeout not found (coreutils)"; exit 1; }
    command -v curl >/dev/null 2>&1 || { echo "[ERR] curl not found"; exit 1; }
}

# Remove previous run results and recreate a clean isolated structure.
reset_dirs() 
{
    rm -rf "$RUN_DIR"
    mkdir -p "$PREFIX_DIR" "$CONF_DIR" "$LOG_DIR" "$WWW_DIR" "$UPLOAD_DIR" "$REQ_DIR" "$RESP_DIR" "$SNAP_DIR"
}

# Create a tiny test website and a seed upload file.
# These files are intentionally simple so request/response behavior is easy to inspect.
prepare_playground() 
{
    # Minimal HTML index page.
    cat > "$WWW_DIR/index.html" <<'EOF'
	<!doctype html>
	<html>
	<body>
		<h1>NGINX isolated playground</h1>
		<p>hello from index</p>
	</body>
	</html>
EOF

    # Plain text static file.
    cat > "$WWW_DIR/hello.txt" <<'EOF'
	hello text file
EOF

    # Seed file inside uploads directory for directory listing tests.
    cat > "$UPLOAD_DIR/seed.txt" <<'EOF'
	seed upload file
EOF
}

# Generate nginx.conf for an isolated local server.
# Important: all paths point inside nginx_lab_run so nothing touches system nginx config.
write_nginx_conf() 
{
    cat > "$CONF_DIR/nginx.conf" <<EOF
	worker_processes  1;
	pid $PREFIX_DIR/nginx.pid;
	error_log $NGINX_BOOTSTRAP_ERR info;

	events {
		worker_connections  128;
	}

	http {
		default_type  text/plain;
		access_log  $LOG_DIR/access.log;
		error_log   $LOG_DIR/error.log info;

		server {
			listen $PORT;
			server_name localhost;

			root $WWW_DIR;
			autoindex on;

			location / {
				try_files \$uri \$uri/ =404;
			}

			location /uploads/ {
				alias $UPLOAD_DIR/;
				autoindex on;
			}
		}
	}
EOF
}

# Wait until nginx is actually ready to accept TCP connections on PORT.
# This avoids race conditions where tests start before nginx is listening.
wait_for_nginx() 
{
    # Try up to ~2 seconds (20 * 0.1s sleep).
    for _ in $(seq 1 20); do
        # /dev/tcp probe succeeds once socket is listening.
        if timeout 1 bash -c "echo > /dev/tcp/127.0.0.1/$PORT" >/dev/null 2>&1; then
            return 0
        fi
        sleep 0.1
    done
    echo "[ERR] nginx did not become ready on port $PORT"
    exit 1
}

# Start isolated nginx using generated config and wait until ready.
start_nginx() 
{
    # Redirect bootstrap output into local log to avoid noisy terminal alerts.
    "$NGINX_BIN" -g "error_log $NGINX_BOOTSTRAP_ERR info;" -p "$PREFIX_DIR/" -c "$CONF_DIR/nginx.conf" >>"$NGINX_BOOTSTRAP_ERR" 2>&1
    wait_for_nginx
}

# Create raw HTTP request files with CRLF line endings.
# These are sent as-is over TCP so you can inspect exact wire format behavior.
write_request_files() 
{
    # GET /
    printf 'GET / HTTP/1.1\r\nHost: 127.0.0.1:%s\r\nConnection: close\r\n\r\n' "$PORT" > "$REQ_DIR/01_get_root.http"

    # GET missing path -> expected 404 in many setups.
    printf 'GET /does-not-exist HTTP/1.1\r\nHost: 127.0.0.1:%s\r\nConnection: close\r\n\r\n' "$PORT" > "$REQ_DIR/02_get_missing.http"

    # GET uploads directory listing.
    printf 'GET /uploads/ HTTP/1.1\r\nHost: 127.0.0.1:%s\r\nConnection: close\r\n\r\n' "$PORT" > "$REQ_DIR/03_get_uploads_index.http"

    # POST / with a tiny body.
    printf 'POST / HTTP/1.1\r\nHost: 127.0.0.1:%s\r\nContent-Type: text/plain\r\nContent-Length: 11\r\nConnection: close\r\n\r\nhello world' "$PORT" > "$REQ_DIR/04_post_root.http"
}

# Save current filesystem state of the playground.
# We keep both a metadata tree view and content hashes.
snapshot_state() 
{
    local tag="$1"

    # tree snapshot format: relative_path|type|size
    find "$PLAYGROUND_DIR" -printf '%P|%y|%s\n' | sort > "$SNAP_DIR/${tag}_tree.txt"

    # If files exist, hash each file so we can detect exact content changes.
    if find "$PLAYGROUND_DIR" -type f | grep -q .; then
        find "$PLAYGROUND_DIR" -type f -print0 | sort -z | xargs -0 sha256sum > "$SNAP_DIR/${tag}_sha256.txt"
    else
        # Create an empty hash file for consistent outputs.
        : > "$SNAP_DIR/${tag}_sha256.txt"
    fi
}

# Send one raw HTTP request file to nginx via netcat and save raw response.
# Also append a small summary block to report.txt.
run_raw_test() 
{
    local name="$1"
    local req_file="$2"
    local resp_file="$RESP_DIR/${name}.txt"

    # timeout prevents hanging forever if a test stalls.
    # || true keeps the script going so one failed case does not kill the run.
    timeout 3 nc 127.0.0.1 "$PORT" < "$req_file" > "$resp_file" || true

    # Append human-readable test summary to the report.
    {
        echo "=== $name ==="
        echo "request:  $req_file"
        echo "response: $resp_file"
        # First response line usually contains status (HTTP/1.1 200 OK, etc.).
        if [ -s "$resp_file" ]; then
            echo "status:   $(head -n 1 "$resp_file")"
        else
            echo "status:   (empty response)"
        fi
        echo
    } >> "$REPORT_FILE"
}

# Capture a raw request generated by curl using netcat as a proxy sink.
# This mirrors your exercise note about seeing exactly what curl sends.
capture_raw_request_from_curl() 
{
    local out_file="$REQ_DIR/00_raw_from_curl.http"

    # Remove any old capture.
    rm -f "$out_file"

    # Start listener in background to record incoming bytes from curl.
    (nc -l 9999 > "$out_file") &
    local nc_pid=$!

    # Use timeout so curl does not hang waiting for a real HTTP proxy response.
    timeout 2 curl http://example.com --http1.0 --proxy http://127.0.0.1:9999 >/dev/null 2>&1 || true

    # Wait for listener to finish (ignore non-zero because timeout can interrupt flow).
    wait "$nc_pid" || true

    # Note capture result in report.
    if [ -s "$out_file" ]; then
        echo "Captured curl raw request at $out_file" >> "$REPORT_FILE"
        echo >> "$REPORT_FILE"
    else
        echo "Could not capture curl request (no output in $out_file)" >> "$REPORT_FILE"
        echo >> "$REPORT_FILE"
    fi
}

# Main orchestration function.
# Order matters: tools -> clean dirs -> data -> config -> start nginx -> tests -> snapshots -> summary.
main() 
{
    # 1) Pre-flight checks.
    require_tools

    # 2) Build clean isolated workspace for this run.
    reset_dirs

    # 3) Prepare filesystem content served by nginx.
    prepare_playground

    # 4) Generate nginx configuration file for this run.
    write_nginx_conf

    # 5) Ensure nginx is stopped automatically when script exits.
    trap cleanup EXIT

    # 6) Start nginx and wait until port is ready.
    start_nginx

    # 7) Initialize report header.
    : > "$REPORT_FILE"
    echo "NGINX lab run" >> "$REPORT_FILE"
    echo "port: $PORT" >> "$REPORT_FILE"
    echo >> "$REPORT_FILE"

    # 8) Capture one raw request produced by curl.
    capture_raw_request_from_curl

    # 9) Create manual raw requests for replay tests.
    write_request_files

    # 10) Snapshot filesystem state before tests.
    snapshot_state "before_tests"

    # 11) Replay requests and capture raw responses.
    run_raw_test "01_get_root" "$REQ_DIR/01_get_root.http"
    run_raw_test "02_get_missing" "$REQ_DIR/02_get_missing.http"
    run_raw_test "03_get_uploads_index" "$REQ_DIR/03_get_uploads_index.http"
    run_raw_test "04_post_root" "$REQ_DIR/04_post_root.http"

    # 12) Snapshot filesystem state after tests.
    snapshot_state "after_tests"

    # 13) Print quick terminal summary with output locations.
    echo "Run complete. Outputs:" 
    echo "  - report:    $REPORT_FILE"
    echo "  - requests:  $REQ_DIR"
    echo "  - responses: $RESP_DIR"
    echo "  - snapshots: $SNAP_DIR"
    echo "  - nginx log: $LOG_DIR"
}

# Script entry point.
main "$@"
